#spring:
#  datasource:
#    url: jdbc:h2:file:~/testdb
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
#  jpa:
#    hibernate:
#      use-new-id-generator-mappings: false
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
spring:
  datasource:
    url: jdbc:h2:file:~/testdb;DATABASE_TO_UPPER=false
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
#    localhost:8080/h2-console